server:
  port: 8881
  tomcat:
    threads:
      max: 50
      min-spare: 5
    keep-alive-timeout: 15s
    connection-timeout: 2s
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/khodabandelu/config-data.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
